POST http://localhost:5000/api/location
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6Ijk2NTMzMTMwODIiLCJpZCI6IjY1ODlhNzYzNDk4NTczNDdkYWUzNTZjZiIsImlhdCI6MTcwNzQ5Njc4NiwiZXhwIjoxNzM5MDMyNzg2fQ.1lzip85S3IhpEAJ9k0zXng5zFIJM8ueeXcAJLRZnAwA
Content-Type: application/json

{
	"location": {
		"type": "Point",
		"coordinates": [18.999221942929235, 72.81735151343756]
	},
	"locationName": "Provider5"
}