POST http://localhost:5000/api/login/verifyUser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6Iis5MTk2NTMzMTMwODIiLCJpZCI6IjY1N2RhN2M0MTYzN2RhODE5ZWRjMDllNCIsImlhdCI6MTcwNzE1MDg3OSwiZXhwIjoxNzM4Njg2ODc5fQ.Gge_X9mjYtLrBmXdcEJsuykTv2o4v2XNKTC6sfr74Oo

# GET http://localhost:5000/api/user
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6Iis5MTcyMTkzMDY5NTYiLCJpZCI6IjY1Mjc4NzRkNTczNWYwNWM0OWFhNzFiYiIsImlhdCI6MTY5NzA5MDAzMiwiZXhwIjoxNzI4NjI2MDMyfQ.QhKjOqbaMlGCoteAlLjCE5i_3zJWmWuNwX8hWewZbhk

# service-provider: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6Iis5MTk2NTMzMTMwODIiLCJpZCI6IjY1MjU2ZDNkZTZiOWM3MDM5YjU0MjBmNiIsImlhdCI6MTY5Njk1Mjg2NSwiZXhwIjoxNzI4NDg4ODY1fQ._tdQ-8zXuBjcVREcYMTDRRaSQC4vmzrFmT2MWFd_8u4
# user: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6Iis5MTk2NTMzMTMwODIiLCJpZCI6IjY1MjQ1MTZmOWQ1ZGEzYjQyOWM0NDIzZSIsImlhdCI6MTY5NjkyNjE3OCwiZXhwIjoxNzI4NDYyMTc4fQ.K2GzqerJARTPCyiL9oWCxg7lx1j4uy7QD4JLK7eSvVg