GET http://localhost:5000/api/carts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6Iis5MTk2NTMzMTMwODIiLCJpZCI6IjY1N2RhN2M0MTYzN2RhODE5ZWRjMDllNCIsImlhdCI6MTcwNzE1MDg3OSwiZXhwIjoxNzM4Njg2ODc5fQ.Gge_X9mjYtLrBmXdcEJsuykTv2o4v2XNKTC6sfr74Oo