DELETE http://localhost:5000/api/carts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6Iis5MTk2NTMzMTMwODIiLCJpZCI6IjY1N2RhN2M0MTYzN2RhODE5ZWRjMDllNCIsImlhdCI6MTcwMjczNDEyMCwiZXhwIjoxNzM0MjcwMTIwfQ.Sy4s4irEdyxrhj6Hs6l1DlJmbjofSEfKQntfDWY1QW8
Content-Type: application/json

{
	"serviceId": "6526ca714ffeb3daaae6839c"
}