POST http://localhost:3000/api/login/verifyUser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6Iis5MTk2NTMzMTMwODIiLCJpZCI6IjY1MjQ1MTZmOWQ1ZGEzYjQyOWM0NDIzZSIsImlhdCI6MTY5NjkyNjE3OCwiZXhwIjoxNzI4NDYyMTc4fQ.K2GzqerJARTPCyiL9oWCxg7lx1j4uy7QD4JLK7eSvVg