GET http://localhost:5000/api/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMTIzIiwiaWQiOiI2NWM3OTYxNDFkY2VlZjVhNDZkYzNlYjgiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MDc1Nzk4ODUsImV4cCI6MTczOTExNTg4NX0.mOtp_ipJhyNTYdAjMRurgwmx1SbjGNxvaLu_0Q575WQ