PUT http://localhost:5000/api/bookedService/65c25173cbf2bd501c8464e1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6Iis5MTk2NTMzMTMwODIiLCJpZCI6IjY1N2RhN2M0MTYzN2RhODE5ZWRjMDllNCIsImlhdCI6MTcwNzIzMTY3OSwiZXhwIjoxNzM4NzY3Njc5fQ.GxT9KzKawAh4zeOMGY__4To9YycRsskxnqrU-Inl--Y
Content-Type: application/json

{
	"deliveryDates": [ "2023-12-20", "2023-12-21", "2023-12-22" ],
	"status": "Cancelled"
}